services:
  - type: web
    name: prometeylabs-telegram-bot
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        value: "8112513772:AAFIsM2RNDEQt5tyYCYAuZgpUsGmZUvP31M"
      - key: ADMIN_ID
        value: "7603163573"
      - key: WEBHOOK_URL
        value: "https://prometeylabs-telegram-bot-90mo.onrender.com"
      - key: ZENEDU_API_URL
        value: https://api.zenedu.io/v1
      - key: ZENEDU_API_KEY
        value: aKKYBIMaR92RXBxfR2Wp12G9CtFIB6k8E9EJabAM883db9a6
      - key: DATABASE_PATH
        value: bot_database.db
      - key: ENVIRONMENT
        value: production 